config/routes.rb
Rails.application.routes.draw do

  get 'landing/index'
  
  get 'users/add_email'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' } 
  
  resources :users, :only => :show
  resources :articles
  resources :categories
  resources :blog, only: [:index, :show, :edit, :update]

  constraints(Subdomain) do
    match '/' => 'blog#show', via: [:get, :patch, :post]
  end

  get '/users/:id/add_email' => 'users#add_email', via: [:get, :patch, :post], :as => :add_user_email

  root 'landing#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user
  has_many :articles
  has_one :picture, as: :imageable

  private
	  def self.reset_sequence!
	    ActiveRecord::Base.connection.execute("DELETE from sqlite_sequence where name = '#{table_name}'")
	  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  before_action :set_blog, only: [:edit, :update]
	before_action :authenticate_user!

	def index
		@user = current_user
    if @user.blog.nil?
		  @blog = build_user_blog_on_first_time_login
    else
      @blog = @user.blog
    end
		@published_articles = @user.blog.articles.where(status: 'published').order("updated_at DESC").page(params[:page]).per(5)
    @categories = Category.all
	end

  def show
    @user = User.where(:name => request.subdomain).first || not_found
  end

  def edit
  end

  def update
   
    respond_to do |format|
      if @blog.update(name: blog_params[:name], description: blog_params[:description]) && 
          @blog.picture.update(name: picture_params[:banner]) && 
            @blog.user.picture.update(name: avatar_params[:avatar])

        format.html { redirect_to blog_index_url, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: blog_index_url }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def not_found
    raise ActionController::RoutingError.new('User Not Found')
  end

  private 
  	def build_user_blog_on_first_time_login
  		if @user.sign_in_count == 1  
				blog = @user.build_blog(attributes = {
  				name: @user.name.capitalize + "'s Blog"
  			} )
        if blog.save
          blog_img = blog.build_picture(name: File.open(Rails.application.config.assets.paths[0]+"/blue1x1.png"))
          blog_img.save!
        end
       

        if @user.picture.nil?
          user_img = @user.build_picture(name: File.open(Rails.application.config.assets.paths[0]+"/grey1x1.png"))
          user_img.save!
        end

			end

      blog
  	end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:name, :description)
    end

    def picture_params
      params.require(:blog).permit(:banner)
    end

    def avatar_params
      params.require(:blog).permit(:avatar)
    end

    def set_blog
      @blog = current_user.blog
      @user = current_user
    end
end

app/views/blog/_form.html.erb
<%= form_for @blog, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label "Blog Banner", :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field "banner" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label "Avatar", :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field "avatar" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                blog_index_path, :class => 'btn' %>
  </div>
  
<% end %>

app/views/blog/edit.html.erb
<%- model_class = Blog -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/blog/index.html.erb
<div class="container">
  <div class="row">
    <div class="span9">
    	<h1><%= @user.blog.name %></h1>
			<span class="blog_description"><%= @user.blog.description %></span>

      <span class="blog_nav">
        <%= link_to 'Edit Blog', edit_blog_path(@blog) %> | 
  			<%= link_to 'Article List', articles_path %> | 
  			<%= link_to 'New Article', new_article_path %> 
      </span>

      <div id="banner">
        <% if @user.blog.picture.present? %>
          <img src=<%= @user.blog.picture.name_url %> alt="banner"/>
        <% else %>
          <%= image_tag "blue1x1.png" %>
        <% end %>
        
      </div>

			<%  @published_articles.each do |article| %>
				<article>
          <h3><%= link_to article.title, article %></h3>
          <div class='published_date'>
            <%= article.updated_at.strftime('%e %b %Y') %>
          </div>
          <% unless article.pictures[0].name.blank? %>
            <img src=<%= article.pictures[0].name_url %> alt="article_image"/>
          <% end %>
					<%= sanitize(article.content.truncate(1000, separator: '</p>')) %>
				<article>
        
			<% end %>
    
     <%= paginate @published_articles %>
    </div>

    <div class="span3 sidebar">
    	<div id="avatar">
        <% if  @user.picture.present? %>
          <img src=<%= @user.picture.name_url %> alt="avatar"/>
        <% else %>
          <%= image_tag "grey1x1.png" %>
        <% end %>
    		
    	</div>
      <h4>Categories</h4>
      <ul class="nav nav-sidebar">
      	<% @categories.each do |category|  %>
      		<li><a href="#"><%= category.name %></a></li>
      	<% end %>
      </ul>

    </div>
  </div>
</div>

app/views/blog/show.html.erb
<h1>Profile</h1>
<h3><%= @user.name %></h3>
<h3><%= @user.email %></h3>