config/routes.rb
Rails.application.routes.draw do

  get 'landing/index'
  
  get 'users/add_email'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' } 
  
  resources :users, :only => :show
  resources :articles
  resources :categories
  resources :blog, only: [:index, :show, :edit, :update]

  constraints(Subdomain) do
    match '/' => 'blog#show', via: [:get, :patch, :post]
  end

  get '/users/:id/add_email' => 'users#add_email', via: [:get, :patch, :post], :as => :add_user_email

  root 'landing#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar_inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">DBlog</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Home", root_path %></li>
          <% unless user_signed_in? %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Register", new_user_registration_path %></li>
          <% else %>
          <li><%= link_to "Blog",  blog_index_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<%= yield %>


</body>
</html>